spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
hibernate:
  validator:
    apply_to_ddl: true
jackson:
  serialization:
    write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
